#!/usr/bin/perl -w

$switch = 0;
if($ARGV[0] eq "-l") {
    $switch = 1;
shift;
$pattern = shift;
} else {
$pattern = shift;
}


$i=0;
if($switch == 1) {
        while ($line = shift) {

            $result = `find . "$line" | xargs grep -irc '$pattern'`;
            print "$result";

            $i++;
        }
    }

if ($switch == 0) {
        while ($line = shift) {

            $result = `find . "$line" | xargs grep -ir '$pattern'`;
            print "$result";

            $i++;
        }
    }

print "\n";

